services:
  dev-db:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextjs-sandbox-dev
    networks:
      - nextjs-sandbox
networks:
  nextjs-sandbox:
