services:
  dev-db:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: revealjs-analytics-dev
    networks:
      - revealjs-analytics
networks:
  revealjs-analytics:
