services:
  dev-db:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: revealjs-pp-tracking-api-dev
    networks:
      - revealjs-pp-tracking-api
networks:
  revealjs-pp-tracking-api:
